### ISSUE TITLE
rake device issue?

### ISSUE THREAD

**Issue by grimmwerks** [digitalfx/motion-carthage#1]
A framework that HAD been a cocoapod has shifted to full carthage support; stumbled upon motion-carthage and seem to have the project working again -- however when I attempted to rake device I got:

```
MaggotEater:cinch-rubymotion grimm$ rake device
Name: cinch
Using profile: /Users/grimm/Documents/__WORK/MOTION/cinch-rubymotion/signing/cinch.mobileprovision
Using certificate: iPhone Developer: Garry Schafer (335X8B6M96)
      Thin WLXBluetoothDevice, CocoaLumberjack
Environment variable not set: TARGET_BUILD_DIR
rake aborted!
Command failed with status (1): [carthage copy-frameworks...]
/Users/grimm/.rvm/gems/ruby-2.3.0/bundler/gems/motion-carthage-1f60d4c1439d/lib/motion-carthage.rb:54:in `copy_frameworks'
/Users/grimm/.rvm/gems/ruby-2.3.0/bundler/gems/motion-carthage-1f60d4c1439d/lib/motion-carthage.rb:26:in `block (2 levels) in <top (required)>'
/Users/grimm/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
/Users/grimm/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => device => archive => build:device => carthage:device
(See full trace by running task with --trace)
MaggotEater:cinch-rubymotion grimm$ 
```

Not sure how to proceed..?

**Comment by grimmwerks** [comment]
Getting this as well now:

```
/Library/RubyMotion/bin/gen_bridge_metadata:12:in `load': cannot load such file -- /Library/RubyMotion/lib/BridgeSupport/usr/bin/gen_bridge_metadata (LoadError)
    from /Library/RubyMotion/bin/gen_bridge_metadata:12:in `<main>'
rake aborted!
Command failed with status (1): [RUBYOPT='' '/Library/RubyMotion/bin/gen_br...]
/Library/RubyMotion/lib/motion/project/xcode_config.rb:472:in `gen_bridge_metadata'
/Library/RubyMotion/lib/motion/project/builder.rb:82:in `block in build'
/Library/RubyMotion/lib/motion/project/builder.rb:77:in `each'
/Library/RubyMotion/lib/motion/project/builder.rb:77:in `build'
/Library/RubyMotion/lib/motion/project/app.rb:78:in `build'
/Users/grimm/.rvm/gems/ruby-2.3.0/gems/motion-cocoapods-1.8.1/lib/motion/project/cocoapods.rb:53:in `build_with_cocoapods'
/Library/RubyMotion/lib/motion/project/template/ios.rb:75:in `block (2 levels) in <top (required)>'
/Users/grimm/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
/Users/grimm/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15 in '<main>'
```

**Comment by pixlwave** [comment]
Hi, sorry but I no longer have an active RubyMotion subscription so am not capable of debugging this. It's very likely that changes within the RM toolchain or Xcode have broken this gem now. Sorry I can't be much more helpful :(

**Comment by MarkVillacampa** [comment]
@grimmwerks I might be able to help, but I'd need steps on how to reproduce this issue.

**Comment by pixlwave** [comment]
@MarkVillacampa Apparently the demo app [CartTest](http://github.com/pixlwave/CartTest) isn't working either. If you're able to get this gem working again I'd be happy to transfer it to you or @Hipbyte if it's useful?

**Comment by pixlwave** [comment]
(Or just fork it and take over from there, either way I'm not going to further this any time soon. It hasn't been packaged up for rubygems.org so the origin probably doesn't matter)
